service: get-it-done-backend

frameworkVersion: "3"

# from kirtanplusone serverless.yml

provider:
  name: aws
  region: "ap-south-1"
  memorySize: 128
  timeout: 10
  endpointType: regional
  architecture: arm64
  versionFunctions: false
  runtime: nodejs16.x
  layers:
    - !Ref ExternalLibsLambdaLayer

custom:
  layerName: get-it-done-backend
  serverless-offline:
    ignoreJWTSignature: true

package:
  individually: true

plugins:
  - serverless-offline
  - serverless-jetpack
  - serverless-stack-output

layers:
  ExternalLibs:
    path: layers
    name: ${self:custom.layerName}-node_modules
    compatibleRuntimes:
      - ${self:provider.runtime}

functions:
  hello:
    handler: functions/hello.handler
    package:
      include:
        - functions/hello.js
      exclude:
        - "**/*"
    events:
      - http:
          path: hello
          method: get
