service: get-it-done-backend

frameworkVersion: "3"

provider:
  name: aws
  region: ap-south-1
  memorySize: 128
  timeout: 5
  endpointType: regional
  architecture: arm64
  versionFunctions: false
  runtime: nodejs16.x
  apiGateway:
    shouldStartNameWithService: true
  environment:
    TodoTable: TodoTable
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:BatchGetItem
        - dynamodb:BatchWriteItem
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TodoTable}"
  layers:
    - !Ref ExternalLibsLambdaLayer

custom:
  allowedHeaders:
    - Accept
    - Content-Length
    - Content-Type
    - X-Amz-Date
    - Authorization
    - X-Api-Key
    - X-Amz-Security-Token
    - X-Amz-User-Agent
  layerName: get-it-done-backend
  serverless-offline:
    ignoreJWTSignature: true
    httpPort: 4000

package:
  individually: true

plugins:
  - serverless-offline
  - serverless-jetpack
  - serverless-stack-output

layers:
  ExternalLibs:
    path: layers
    name: ${self:custom.layerName}-node_modules
    compatibleRuntimes:
      - ${self:provider.runtime}

resources:
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TodoTable}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          # - AttributeName: timestamp
          #   AttributeType: N
          - AttributeName: noteId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: noteId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        # GlobalSecondaryIndexes:
        #   - IndexName: noteId-index
        #     KeySchema:
        #       - AttributeName: noteId
        #         KeyType: HASH
        #     Projection:
        #       ProjectionType: ALL
        #     ProvisionedThroughput:
        #       ReadCapacityUnits: 1
        #       WriteCapacityUnits: 1

functions:
  add-todo:
    handler: functions/add-todo.handler
    package:
      include:
        - functions/add-todo.js
        - functions/util.js
      exclude:
        - "**/*"
    events:
      - http:
          path: todo
          method: post
          cors:
            origin: "*"
            headers: ${self:custom.allowedHeaders}
  add-todos:
    handler: functions/add-todos.handler
    package:
      include:
        - functions/add-todos.js
        - functions/util.js
      exclude:
        - "**/*"
    events:
      - http:
          path: todos
          method: post
          cors:
            origin: "*"
            headers: ${self:custom.allowedHeaders}
